# Generated by Django 2.2 on 2019-09-21 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookGuest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100, verbose_name='Name')),
                ('email', models.EmailField(max_length=100, verbose_name='Email')),
                ('status', models.TextField(choices=[('active', 'active'), ('blocked', 'blocked')], default='active', max_length=40, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Time of add')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Time of update')),
            ],
        ),
    ]
